<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVToWmar\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVToWmar/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVToWmar.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVToWmar\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVToWmar\App_KernelDevDebugContainer([
    'container.build_hash' => 'VToWmar',
    'container.build_id' => '28656d78',
    'container.build_time' => 1615795790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVToWmar');
