<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFI3x0p7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFI3x0p7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFI3x0p7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFI3x0p7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFI3x0p7\App_KernelDevDebugContainer([
    'container.build_hash' => 'FI3x0p7',
    'container.build_id' => 'b24420a8',
    'container.build_time' => 1615706116,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFI3x0p7');
